---
apiVersion: v2
appVersion: 1.0.0
description: Streams graphic applications/games (retroarch, firefox, steam) running on Kubernetes
name: games-on-whales
version: 2.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - games-on-whales
  - steam
  - X11
  - pulse
  - stream
  - retroarch
home: https://github.com/teo/helm-charts/tree/main/charts/apps/games-on-whales
icon: https://raw.githubusercontent.com/teo/helm-charts/gh-pages/icons/gow-logo.png
sources:
  - https://github.com/games-on-whales/gow
maintainers:
  - name: teo
    email: teo@kde.org
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 1.5.1

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        **BREAKING**: Updated library version to 1.0.1.
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
